export default function(){
    return[
        {
            id: 1,
            name: 'lorem ipsum 1',
            description: 'Lorem lorem lorem lorem lorem ipsum sit amet dolor',
            author: 'admin',
            like: 6,
            dislike: 2,
            liked: true,
            disliked: false,
        },
        {
            id: 2,
            name: 'lorem ipsum 2',
            description: 'Lorem lorem lorem lorem lorem ipsum sit amet dolor',
            author: 'admin',
            like: 11,
            dislike: 0,
            liked: false,
            disliked: true,
        },
        {
            id: 3,
            name: 'lorem ipsum 3',
            description: 'Lorem lorem lorem lorem lorem ipsum sit amet dolor',
            author: 'admin',
            like: 6,
            dislike: 15,
            liked: true,
            disliked: false,
        },
        {
            id: 4,
            name: 'lorem ipsum 4',
            description: 'Lorem lorem lorem lorem lorem ipsum sit amet dolor',
            author: 'admin',
            like: 6,
            dislike: -4,
            liked: false,
            disliked: false,
        },
        {
            id: 5,
            name: 'lorem ipsum 5',
            description: 'Lorem lorem lorem lorem lorem ipsum sit amet dolor',
            author: 'admin',
            like: 11,
            dislike: 0,
            liked: false,
            disliked: true,
        },
        {
            id: 6,
            name: 'lorem ipsum 6',
            description: 'Lorem lorem lorem lorem lorem ipsum sit amet dolor',
            author: 'admin',
            like: 100,
            dislike: 15,
            liked: true,
            disliked: false,
        },
    ]
}